#리밋레인지

apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: develop
spec:
  limits:
  - default: 
      memory: 512Mi #리미트
    defaultRequest:
      memory: 216Mi #요청
    type: Container