#CPU Memory 제한.

apiVersion: v1
kind: Pod
metadata:
  name: high-priority
spec:
  containers:
  - name: high-priority
    image: ubuntu
    resources:
      requests:
        memory: 500Mi
        cpu: "200m"
